// <auto-generated />
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260226161600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrew Hunt, David Thomas",
                            CreatedAt = new DateTime(2026, 2, 26, 16, 15, 59, 597, DateTimeKind.Utc).AddTicks(8836),
                            Description = "A guide to software development best practices.",
                            Title = "The Pragmatic Programmer",
                            UpdatedAt = new DateTime(2026, 2, 26, 16, 15, 59, 597, DateTimeKind.Utc).AddTicks(8836)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert C. Martin",
                            CreatedAt = new DateTime(2026, 2, 26, 16, 15, 59, 597, DateTimeKind.Utc).AddTicks(8839),
                            Description = "A handbook of agile software craftsmanship.",
                            Title = "Clean Code",
                            UpdatedAt = new DateTime(2026, 2, 26, 16, 15, 59, 597, DateTimeKind.Utc).AddTicks(8839)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
